import '../styles/globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import { ThemeProvider } from '@/components/providers/theme-provider';
import { cn } from '@/lib/utils';

const font = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Andeh',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(font.className)}>
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          storageKey='andeh-theme'
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
